### ISSUE TITLE
"node_name_for_sr" is unclear

### ISSUE THREAD

**Issue by baardev** [HaydenReeve/ComfyUI-Better-Strings#1]
I have two nodes that have the exact same name, which is not uncommon.  For example, two ksamplers, and in the properties list, they both have the same value of "KSampler (Efficient)" for "Node name for S&R", which I assume is what you mean by "node_name_for_sr".  How do I define which of these identically named nodes I want to grab the value from?

**Comment by HaydenReeve** [comment]
Thanks for reporting! I'll look into this for you tonight. 😊

I think I understand what is happening. I might need to update a unique key for the class if there's a clash with another custom node.

Strange though, as I do use the "KSampler (Efficient)" nodes as well and haven't seen the issue.

This error `node_name_for_sr` is Comfy specific, so I'll have to dig into what is actually going on here.

**Comment by HaydenReeve** [comment]
Do you have an example workflow where you are getting this issue? What custom nodes do you currently have loaded?

The issue you've encountered doesn't appear to be to do my implementation.

If you're chasing a `node_name_for_sr` that refers to this property, which you can get by right-clicking on a node.

![image](https://github.com/HaydenReeve/ComfyUI-Better-Strings/assets/39004735/62c466aa-bc1e-4a8e-8166-6c4cc989e68f)

You can rename this to reference a node directly and disambiguate between nodes with the same default name.

**Comment by baardev** [comment]
Embarrassingly, I did not realize I could rename the S&R name :/  Renaming the first  KSampler  to "KS1" and the second to "KS2" fixed the problem.

Thank you
